### ISSUE TITLE
Discussion: 'Test' storage indices across all config access levels

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/cpg-infrastructure#39]
X-posted from [here](https://github.com/populationgenomics/analysis-runner/pull/579#issuecomment-1407822063)

- The per-dataset infra configs contain absolute paths to the main/web/tmp etc buckets under the `storage` key.
- There's some redundancy, e.g. the `tob-wgs` dataset will have the same content in `storage.default` and `storage.tob-wgs`
- The standard/full permission versions of these config files also contain a `test` category, i.e. `storage.default.test` and `storage.tob-wgs.test` have the same content.
- The test versions of the same configs don't have a test suffix - the default path key contains test paths, with no more granular key for explicitly test bucket paths. 

In this pretty niche situation I'd like to run with standard permissions, and write to the test bucket with as little manual path manipulation as possible so as not to undermine the effort put in to polishing the configs. I though there was now a way to do this using the cpg-utils `output/dataset_path` methods but looking closer I don't think that's true.

It looks like there was a [`test` argument planned for dataset_path](https://github.com/populationgenomics/cpg-utils/blob/main/cpg_utils/hail_batch.py#L132-L133), but this isn't actually implemented. Without the `test` paths published in the test config files, it's not easy to implement this argument to switch output to a test bucket - any code expecting a test path would break when run in `test`, making copying scripts hard to test (ironic?).

Q. - Can we justify implementing a `storage.test` index in the config files across all access levels?

Context - hard path replacement from `-main` to `-test` in these scripts was working before, and I can just go back to that, no drama. I don't know any other situations where we are likely to make use of this behaviour.

**Comment by illusional** [comment]
Closing this, as resolved in cpg-utils#128.
